import { CategoryInfo, CategoryBudget, Transaction } from './types';

// Transfer-type categories (never counted as expense or income)
export const TRANSFER_CATS = new Set(['withdrawal', 'transfer', 'bank']);
// Income-type categories
export const INCOME_CATS = new Set(['salary', 'freelance', 'investment']);

export const CATS: Record<string, CategoryInfo> = {
  food:         { label: 'Food',          icon: '🍔', color: '#f97316' },
  coffee:       { label: 'Coffee',        icon: '☕', color: '#a78bfa' },
  grocery:      { label: 'Grocery',       icon: '🛒', color: '#22c55e' },
  transport:    { label: 'Transport',     icon: '🚗', color: '#3b82f6' },
  car:          { label: 'Car',           icon: '🚙', color: '#4f8ef7' },
  health:       { label: 'Health',        icon: '🏥', color: '#2dd4bf' },
  bills:        { label: 'Bills',         icon: '💡', color: '#fbbf24' },
  rent:         { label: 'Rent',          icon: '🏠', color: '#f472b6' },
  entertainment:{ label: 'Entertainment', icon: '🎬', color: '#c084fc' },
  shopping:     { label: 'Shopping',      icon: '🛍', color: '#fb7185' },
  education:    { label: 'Education',     icon: '📚', color: '#60a5fa' },
  travel:       { label: 'Travel',        icon: '✈️', color: '#34d399' },
  gift:         { label: 'Gift',          icon: '🎁', color: '#f87171' },
  salary:       { label: 'Salary',        icon: '💰', color: '#4ade80' },
  freelance:    { label: 'Freelance',     icon: '💼', color: '#a3e635' },
  investment:   { label: 'Investment',    icon: '📈', color: '#38bdf8' },
  bank:         { label: 'Bank',          icon: '🏦', color: '#818cf8' },
  fees:         { label: 'Fees',          icon: '💳', color: '#fb923c' },
  withdrawal:   { label: 'Withdrawal',    icon: '💵', color: '#94a3b8' },
  transfer:     { label: 'Transfer',      icon: '💸', color: '#64748b' },
  family:       { label: 'Family',        icon: '❤️', color: '#f43f5e' },
  pets:         { label: 'Pets',          icon: '🐶', color: '#d97706' },
  subscription: { label: 'Subscription',  icon: '📱', color: '#7c3aed' },
  online:       { label: 'Online Shop',   icon: '📦', color: '#0ea5e9' },
  taxes:        { label: 'Taxes',         icon: '📋', color: '#dc2626' },
  maintenance:  { label: 'Maintenance',   icon: '🔧', color: '#78716c' },
  other:        { label: 'Other',         icon: '📦', color: '#8895aa' },
};

export const BUDGETS: CategoryBudget = {
  food: 500,
  coffee: 100,
  grocery: 450,
  transport: 200,
  car: 300,
  health: 300,
  bills: 400,
  rent: 1200,
  entertainment: 150,
  shopping: 300,
  education: 100,
  travel: 500,
  gift: 150,
  salary: 0,
  freelance: 0,
  investment: 0,
  bank: 0,
  fees: 50,
  withdrawal: 0,
  transfer: 0,
  family: 200,
  pets: 100,
  subscription: 80,
  online: 200,
  taxes: 300,
  maintenance: 150,
  other: 200,
};

// Keyword mapping for automated categorization based on transaction titles
export const KW: Record<string, string> = {
  pizza: 'food', burger: 'food', kebab: 'food', sandwich: 'food', meal: 'food', lunch: 'food',
  dinner: 'food', breakfast: 'food', restaurant: 'food', food: 'food', eat: 'food', shawarma: 'food',
  coffee: 'coffee', cafe: 'coffee', espresso: 'coffee', latte: 'coffee', cappuccino: 'coffee', tea: 'coffee', starbucks: 'coffee',
  grocery: 'grocery', groceries: 'grocery', supermarket: 'grocery', market: 'grocery', carrefour: 'grocery', monoprix: 'grocery', mg: 'grocery',
  taxi: 'transport', uber: 'transport', lyft: 'transport', metro: 'transport', bus: 'transport', transport: 'transport', ticket: 'transport', train: 'transport', tram: 'transport', bolt: 'transport',
  car: 'car', petrol: 'car', fuel: 'car', parking: 'car', garage: 'car', mechanic: 'car', oil: 'car', gasoline: 'car',
  pharmacy: 'health', doctor: 'health', hospital: 'health', medical: 'health', dentist: 'health', medicine: 'health', clinic: 'health', health: 'health',
  electricity: 'bills', water: 'bills', internet: 'bills', phone: 'bills', bill: 'bills', bills: 'bills', invoice: 'bills', utility: 'bills', telecom: 'bills', steg: 'bills', sonede: 'bills',
  rent: 'rent', loyer: 'rent', appartement: 'rent',
  cinema: 'entertainment', netflix: 'entertainment', spotify: 'entertainment', game: 'entertainment', entertainment: 'entertainment', movie: 'entertainment', concert: 'entertainment', theater: 'entertainment',
  shopping: 'shopping', zara: 'shopping', clothes: 'shopping', vetement: 'shopping', malls: 'shopping',
  school: 'education', university: 'education', book: 'education', cours: 'education', formation: 'education', education: 'education', tuition: 'education',
  flight: 'travel', hotel: 'travel', travel: 'travel', voyage: 'travel', airbnb: 'travel', ticket_plane: 'travel',
  gift: 'gift', cadeau: 'gift', present: 'gift',
  salary: 'salary', salaire: 'salary', paie: 'salary', virement_salaire: 'salary', pay: 'salary', paycheck: 'salary',
  freelance: 'freelance', invoice_out: 'freelance', contract: 'freelance', upwork: 'freelance', client: 'freelance',
  investment: 'investment', bourse: 'investment', crypto: 'investment', epargne: 'investment', stocks: 'investment', div: 'investment',
  bank: 'bank', banque: 'bank', agence: 'bank',
  frais: 'fees', fees: 'fees', commission: 'fees', fee: 'fees',
  retrait: 'withdrawal', withdrawal: 'withdrawal', atm: 'withdrawal', cash_out: 'withdrawal',
  virement: 'transfer', transfer: 'transfer',
  famille: 'family', family: 'family', parent: 'family', kids: 'family',
  pet: 'pets', dog: 'pets', cat: 'pets', vet: 'pets', pets: 'pets', petfood: 'pets',
  abonnement: 'subscription', subscription: 'subscription', apple: 'subscription', google: 'subscription', cloud: 'subscription',
  amazon: 'online', aliexpress: 'online', jumia: 'online', livraison: 'online', delivery: 'online', shein: 'online',
  impot: 'taxes', tax: 'taxes', taxes: 'taxes', tax_bill: 'taxes',
  maintenance: 'maintenance', reparation: 'maintenance', plumber: 'maintenance', electrician: 'maintenance',
};

export const PM_CONFIGS: Record<string, { icon: string, color: string }> = {
  'Cash':            { icon: '💵', color: '#22c55e' },
  'Card':            { icon: '💳', color: '#3b82f6' },
  'Bank Transfer':   { icon: '🏦', color: '#a78bfa' },
  'Mobile Payment':  { icon: '📱', color: '#fb923c' },
};

// Generates high-quality mock data dynamically for the current period (June 2026 and previous month May 2026)
export const getMockTransactions = (): Transaction[] => {
  return [
    {
      id: 'tx-1',
      date: '2026-06-01',
      time: '08:30',
      desc: 'Monthly Salary Deposit',
      notes: 'Main employer bank transfer',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'income',
      cat: 'salary',
      amount: 4500,
    },
    {
      id: 'tx-2',
      date: '2026-06-01',
      time: '12:00',
      desc: 'Apartment Rent Payment',
      notes: 'Automatic wire transfer',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'expense',
      cat: 'rent',
      amount: 1100,
    },
    {
      id: 'tx-3',
      date: '2026-06-03',
      time: '18:15',
      desc: 'Carrefour Groceries Weekly',
      notes: 'Weekly stock-up',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'grocery',
      amount: 185.500,
    },
    {
      id: 'tx-4',
      date: '2026-06-04',
      time: '09:45',
      desc: 'Morning Espresso & Croissant',
      notes: 'Café de Paris',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'coffee',
      amount: 8.500,
    },
    {
      id: 'tx-5',
      date: '2026-06-05',
      time: '15:20',
      desc: 'STEG Electricity Bill',
      notes: 'May electricity consumption',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'bills',
      amount: 145.200,
    },
    {
      id: 'tx-6',
      date: '2026-06-07',
      time: '14:00',
      desc: 'Freelance Design Project',
      notes: 'Website redesign for local client',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'income',
      cat: 'freelance',
      amount: 1200,
    },
    {
      id: 'tx-7',
      date: '2026-06-08',
      time: '17:30',
      desc: 'Gasoline Station Fuel',
      notes: 'Total station fill-up',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'car',
      amount: 110,
    },
    {
      id: 'tx-8',
      date: '2026-06-09',
      time: '20:30',
      desc: 'Sushi Dinner with Friends',
      notes: 'Splitting was not available',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'food',
      amount: 140.000,
    },
    {
      id: 'tx-9',
      date: '2026-06-10',
      time: '10:00',
      desc: 'ATM Cash Withdrawal',
      notes: 'Transferred bank funds to cash wallet',
      pm: 'Cash',
      account: 'Bank',
      type: 'transfer',
      cat: 'withdrawal',
      amount: 300,
      fromAccount: 'Bank',
      toAccount: 'Cash',
    },
    {
      id: 'tx-10',
      date: '2026-06-11',
      time: '11:15',
      desc: 'Ooredoo Internet Subscription',
      notes: 'Fibre broadband subscription',
      pm: 'Mobile Payment',
      account: 'Bank',
      type: 'expense',
      cat: 'bills',
      amount: 55,
    },
    {
      id: 'tx-11',
      date: '2026-06-12',
      time: '16:40',
      desc: 'Cat Food and Vet Check',
      notes: 'Dr. Salem clinic',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'pets',
      amount: 95.000,
    },
    {
      id: 'tx-12',
      date: '2026-06-14',
      time: '19:00',
      desc: 'Zara Summer Collection',
      notes: 'New shirts and trousers',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'shopping',
      amount: 320.000,
    },
    {
      id: 'tx-13',
      date: '2026-06-15',
      time: '08:45',
      desc: 'Cappuccino Morning',
      notes: 'Daily boost',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'coffee',
      amount: 6.500,
    },
    {
      id: 'tx-14',
      date: '2026-06-16',
      time: '14:30',
      desc: 'Plumbing Repair Kitchen Sink',
      notes: 'Leaking pipe replacement',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'maintenance',
      amount: 80,
    },
    {
      id: 'tx-15',
      date: '2026-06-18',
      time: '13:00',
      desc: 'Weekly Groceries Monoprix',
      notes: 'Fresh veggies and meat',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'grocery',
      amount: 165.400,
    },
    {
      id: 'tx-16',
      date: '2026-06-19',
      time: '19:45',
      desc: 'Cinema & Popcorn Night',
      notes: 'Pathé Tunis City',
      pm: 'Mobile Payment',
      account: 'Card',
      type: 'expense',
      cat: 'entertainment',
      amount: 42,
    },
    {
      id: 'tx-17',
      date: '2026-06-20',
      time: '11:00',
      desc: 'Crypto Purchase',
      notes: 'BTC long-term investment',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'expense',
      cat: 'investment',
      amount: 250,
    },
    {
      id: 'tx-18',
      date: '2026-06-22',
      time: '17:00',
      desc: 'Taxi Bolt Ride',
      notes: 'Return from business meeting',
      pm: 'Mobile Payment',
      account: 'Card',
      type: 'expense',
      cat: 'transport',
      amount: 22.500,
    },
    {
      id: 'tx-19',
      date: '2026-06-24',
      time: '12:30',
      desc: 'Gourmet Burger Lunch',
      notes: 'Chili burger custom',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'food',
      amount: 28.500,
    },
    {
      id: 'tx-20',
      date: '2026-06-25',
      time: '15:00',
      desc: 'Car Brake Pads Replacement',
      notes: 'Peugeot service agency',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'car',
      amount: 340.000,
    },
    {
      id: 'tx-21',
      date: '2026-06-26',
      time: '10:00',
      desc: 'Google Cloud Platform Bill',
      notes: 'Dev resources storage',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'subscription',
      amount: 24.800,
    },
    {
      id: 'tx-22',
      date: '2026-06-27',
      time: '18:00',
      desc: 'Birthday Gift for Mother',
      notes: 'Perfume box set',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'gift',
      amount: 195,
    },
    {
      id: 'tx-23',
      date: '2026-06-28',
      time: '13:00',
      desc: 'Sunday Roast Food Delivery',
      notes: 'Jumia Food order',
      pm: 'Mobile Payment',
      account: 'Card',
      type: 'expense',
      cat: 'food',
      amount: 48.900,
    },
    {
      id: 'tx-24',
      date: '2026-06-29',
      time: '09:00',
      desc: 'Double Espresso Shot',
      notes: 'Daily morning ritual',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'coffee',
      amount: 5.500,
    },
    {
      id: 'tx-25',
      date: '2026-06-30',
      time: '11:10',
      desc: 'Local Clinic Consultation',
      notes: 'Seasonal allergy prescription',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'health',
      amount: 70,
    },
    // MAY 2026 TRANSACTIONS FOR HISTORIC VALUE COMPILATION
    {
      id: 'tx-may-1',
      date: '2026-05-01',
      time: '08:30',
      desc: 'May Base Salary Deposit',
      notes: 'Direct deposit',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'income',
      cat: 'salary',
      amount: 4500,
    },
    {
      id: 'tx-may-2',
      date: '2026-05-01',
      time: '12:00',
      desc: 'Apartment Rent Payment May',
      notes: 'Automatic wire transfer',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'expense',
      cat: 'rent',
      amount: 1100,
    },
    {
      id: 'tx-may-3',
      date: '2026-05-04',
      time: '15:00',
      desc: 'Monoprix Grocery Fill',
      notes: 'Monthly staples',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'grocery',
      amount: 220,
    },
    {
      id: 'tx-may-10',
      date: '2026-05-10',
      time: '09:00',
      desc: 'MacBook Stand Jumia',
      notes: 'Aluminum laptop stand',
      pm: 'Mobile Payment',
      account: 'Card',
      type: 'expense',
      cat: 'online',
      amount: 115,
    },
    {
      id: 'tx-may-15',
      date: '2026-05-15',
      time: '21:00',
      desc: 'Dinner and Drinks',
      notes: 'L\'Atelier Restaurant',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'food',
      amount: 195,
    },
    {
      id: 'tx-may-20',
      date: '2026-05-20',
      time: '16:00',
      desc: 'Freelance Graphics Package',
      notes: 'Logo & assets project',
      pm: 'Bank Transfer',
      account: 'Bank',
      type: 'income',
      cat: 'freelance',
      amount: 800,
    },
    {
      id: 'tx-may-25',
      date: '2026-05-25',
      time: '10:00',
      desc: 'Car Oil and Filter Change',
      notes: 'Shell station quick service',
      pm: 'Cash',
      account: 'Cash',
      type: 'expense',
      cat: 'car',
      amount: 120,
    },
    {
      id: 'tx-may-28',
      date: '2026-05-28',
      time: '14:00',
      desc: 'Dentist Hygiene Session',
      notes: 'Routine checkup and scaler',
      pm: 'Card',
      account: 'Card',
      type: 'expense',
      cat: 'health',
      amount: 150,
    }
  ];
};
